author_email: administrator@internal.subterfuge.biz
author_id: 1
author_name: administrator
automations_enabled: false
created_at: '2025-05-25T18:08:30Z'
description: Returns top 10 applications or processes hogging memory the most.
discard_data: false
id: 33
interval: 0
labels_include_any: null
logging: snapshot
min_osquery_version: ''
name: Get applications hogging memory
observer_can_run: false
packs: []
platform: darwin, linux, windows
query: SELECT pid, name, ROUND((total_size * '10e-7'), 2) AS memory_used FROM processes
  ORDER BY total_size DESC LIMIT 10;
saved: true
stats:
  system_time_p50: 20
  system_time_p95: 170
  total_executions: 27
  user_time_p50: 30
  user_time_p95: 270
team_id: null
updated_at: '2025-05-25T18:08:30Z'
