author_email: administrator@internal.subterfuge.biz
author_id: 1
author_name: administrator
automations_enabled: false
created_at: '2025-05-25T18:08:30Z'
description: Lists the currently enabled applications configured to handle mailto,
  http and ftp schemes.
discard_data: false
id: 45
interval: 0
labels_include_any: null
logging: snapshot
min_osquery_version: ''
name: Identify the default mail, http and ftp applications
observer_can_run: false
packs: []
platform: darwin
query: SELECT * FROM app_schemes WHERE (scheme='mailto' OR scheme='http' OR scheme='ftp')
  AND enabled='1';
saved: true
stats:
  system_time_p50: null
  system_time_p95: null
  total_executions: 0
  user_time_p50: null
  user_time_p95: null
team_id: null
updated_at: '2025-05-25T18:08:30Z'
