author_email: administrator@internal.subterfuge.biz
author_id: 1
author_name: administrator
automations_enabled: false
created_at: '2025-05-25T18:08:30Z'
description: Returns applications that were opened within the last 24 hours starting
  with the last opened application.
discard_data: false
id: 36
interval: 0
labels_include_any: null
logging: snapshot
min_osquery_version: ''
name: Get applications that were opened within the last 24 hours
observer_can_run: false
packs: []
platform: darwin
query: SELECT * FROM apps WHERE last_opened_time > (( SELECT unix_time FROM time )
  - 86400 ) ORDER BY last_opened_time DESC;
saved: true
stats:
  system_time_p50: null
  system_time_p95: null
  total_executions: 0
  user_time_p50: null
  user_time_p95: null
team_id: null
updated_at: '2025-05-25T18:08:30Z'
